project:
  type: website
  output-dir: docs
  resources:
    - cv.pdf
    
website:
  title: "Yin-Yun Li"
  navbar:
    background: "#4B5358" 
    foreground: "white"   
    right:
      - text: Home
        href: index.qmd
      - text: CV
        href: cv.qmd
      # - text: Research
      #   href: about.qmd
      - text: Notes
        href: notes.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full