project:
  type: website
  output-dir: docs
  resources:
    - CV.pdf
    
website:
  title: "Yin-Yun Li"
  navbar:
    background: dark
    right:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      # - text: Research
      #   href: about.qmd
      # - text: Notes
      #   href: notes.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true